services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis

  web:
    build: .
    command: >
      bash -c "
        bundle install &&
        bundle exec rails db:prepare &&
        rm -f tmp/pids/server.pid &&
        yarn install &&
        ./bin/dev
      "
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
  bundle_data:
  node_modules:
  redis:
